### ISSUE TITLE
Can't resolve 'pnpapi' with webpack 5.4.0

### ISSUE THREAD

**Issue by dstampher** [webpack/enhanced-resolve#263] opened 2020-11-14 11:01 UTC
```
ERROR in ./node_modules/enhanced-resolve/lib/ResolverFactory.js 118:9-26
Module not found: Error: Can't resolve 'pnpapi' in 'C:\Users\david\Projects\electron-react @ ./node_modules/enhanced-resolve/lib/index.js 10:24-52
 @ ./node_modules/webpack/lib/ResolverFactory.js 8:16-59
 @ ./node_modules/webpack/lib/Compiler.js 25:24-52
 @ ./node_modules/webpack/lib/index.js 114:9-30
 @ ./src/js/App.js 2:0-35
 @ ./src/js/index.js 3:0-24 5:50-53
```

Here's my package.json as well

```
{
  "name": "electron-react",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "watch": "webpack --config webpack.common.js --watch",
    "start": "electron ."
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "electron": "^10.1.5",
    "react": "^17.0.1",
    "react-dom": "^17.0.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.3",
    "@babel/preset-env": "^7.12.1",
    "@babel/preset-react": "^7.12.5",
    "babel-loader": "^8.2.1",
    "css-loader": "^5.0.1",
    "electron-reload": "^1.5.0",
    "sass": "^1.29.0",
    "sass-loader": "^10.1.0",
    "style-loader": "^2.0.0",
    "webpack": "^5.4.0",
    "webpack-cli": "^4.2.0"
  }
}
```

From what I've heard, pnpapi is built into webpack now, and that might be causing some conflict?  I commented out line 118 in lib/ResolverFactory.js and webpack compiles fine after that.

**Comment by sokra** [comment] 2020-11-15 18:32
Whats in this line? src/js/App.js 2:0-35

**Comment by dstampher** [comment] 2020-11-15 19:14
@sokra ResolverFactory.js 118

**Comment by BradBailey-web** [comment] 2020-12-03 18:33
I stopped getting the aformentioned error by changing 

`./node_modules/webpack/node_modules/enhanced-resolve/lib/ResolverFactory.js 118:9-26`
to 
`return require("./PnpPlugin").PnpApiImpl`

**Comment by RAMKUMARDANE** [comment] 2020-12-05 14:31
> return require("./PnpPlugin").PnpApiImpl

yes it removes the error,

**Comment by laibao101** [comment] 2021-01-20 08:44
webpack 5.16.0
i use webpack to pack webpack into a bundle.js。it has a same problem。

**Comment by alexander-akait** [comment] 2021-01-20 11:32
Somebody can create reproducible test repo?

**Comment by ferdinando-ferreira** [comment] 2021-03-24 05:25
> Somebody can create reproducible test repo?

@alexander-akait : https://github.com/ferdinando-ferreira/enhanced-resolve-pnpapi-bug

```
git clone https://github.com/ferdinando-ferreira/enhanced-resolve-pnpapi-bug.git enhanced-resolve-pnpapi-bug
cd enhanced-resolve-pnpapi-bug
npm install
npm run build
```

**Comment by barak007** [comment] 2021-04-18 08:24
this is fixed in master but is not released....https://github.com/webpack/enhanced-resolve/commit/f08fe3f1a22c90c722eca14b38a9300ad00c62e8

**Comment by zemlanin** [comment] 2021-05-21 07:50
https://github.com/webpack/enhanced-resolve/commit/f08fe3f1a22c90c722eca14b38a9300ad00c62e8 seems to be released in [`5.8.0`](https://github.com/webpack/enhanced-resolve/releases/tag/v5.8.0)

**Closed** 2021-05-21 13:28 UTC

**Comment by DavidTanner** [comment] 2022-03-07 22:11
I'm still getting this error, but with yarn berry.

```
Cannot find module 'pnpapi' from 'rootDir/.yarn/cache/enhanced-resolve-npm-5.9.2-ffd6aeacc7-792b7a01ab.zip/node_modules/enhanced-resolve/lib'

Require stack:
  rootDir/.yarn/cache/enhanced-resolve-npm-5.9.2-ffd6aeacc7-792b7a01ab.zip/node_modules/enhanced-resolve/lib/index.js
  rootDir/.yarn/__virtual__/webpack-virtual-71baba393b/0/cache/webpack-npm-5.70.0-5fea152450-00439884a9.zip/node_modules/webpack/lib/CacheFacade.js
  rootDir/.yarn/__virtual__/webpack-virtual-71baba393b/0/cache/webpack-npm-5.70.0-5fea152450-00439884a9.zip/node_modules/webpack/lib/Compiler.js
  rootDir/.yarn/__virtual__/webpack-virtual-71baba393b/0/cache/webpack-npm-5.70.0-5fea152450-00439884a9.zip/node_modules/webpack/lib/webpack.js
  rootDir/.yarn/__virtual__/webpack-virtual-71baba393b/0/cache/webpack-npm-5.70.0-5fea152450-00439884a9.zip/node_modules/webpack/lib/index.js
  src/index.ts
  test/index.test.ts

  at resolveSync (../../.yarn/cache/resolve-patch-bad885c6ea-c79ecaea36.zip/node_modules/resolve/lib/sync.js:111:15)
```

**Comment by jscheid** [comment] 2022-03-27 09:51
Exact same error as @DavidTanner here, using enhanced-resolve 5.9.2, Yarn 3.2.0 and Jest 27.5.1. Repro: https://github.com/jscheid/enhanced-resolve-263

**Comment by louisscruz** [comment] 2022-06-03 05:52
I'm currently experiencing the same as @jscheid with the same exact versions of those dependencies.

**Comment by louisscruz** [comment] 2022-06-14 19:41
I've opened https://github.com/webpack/enhanced-resolve/pull/349, which seems to be patching the issue locally for me. There's got to be a better way, but maybe the approach taken in that PR is good enough to provide a workaround for now?

**Comment by louisscruz** [comment] 2022-06-14 21:22
Aha! Things seem to work as expected if `require('pnpapi')` is changed to `require('module').findPnpApi(process.cwd())`. The PR has been updated.

**Comment by vankop** [comment] 2022-06-20 13:22
@louisscruz please try latest webpack

**Comment by albertyfwu** [comment] 2022-07-14 00:29
@vankop I'm on the latest webpack (5.73.0) but still seeing this error.

**Comment by chinesehemp** [comment] 2022-11-14 10:56
Hi all, I'm having the same problem. I'm on yarn v1.22.19, with enhanced-resolve 5.10.0.

`node_modules/enhanced-resolve/lib/ResolverFactory.js` on line 126 is still reading `return require("pnpapi"); // eslint-disable-line node/no-missing-require`

Is there a way to fix this without locally hacking my node_modules?
