### ISSUE TITLE
Is Bower supported?

### ISSUE THREAD

**Issue by pornel** [webpack/enhanced-resolve#30] opened 2016-06-10 15:52 UTC
I'm trying to mix npm and bower components in webpack2. 

I have:
- `lib/entry_point.js` with `require('bowerlib')` intended for bower, and other npm requires
- `bower_components/bowerlib/main.js` with `require('raven-js')`
- `bower_components/raven-js` that specifies `dist/raven.js` as `main`.
- `node_modules` with lots of npm modules installed

I've tried:
- out of the box webpack2: can't find `bowerlib`
- config with `resolve: {modules: [ __dirname + '/bower_components', 'node_modules']}` - still can't find `bowerlib`
- config with `resolve: {modules: [ __dirname + '/bower_components', 'node_modules'],mainFiles: ['index', 'main']}` — it can find `bowerlib`, but can't find `raven-js`.
- `resolve: {modules: [ __dirname + '/bower_components', 'node_modules'],mainFiles: ['index', 'main'],descriptionFiles: ["bower.json", "package.json"]}` — hundreds of errors caused by failure to load npm modules from `node_modules` that worked otherwise.

Is it possible to use bower components? Is it possible with configuration, or do I have to write a custom plugin?

**Comment by readme42** [comment] 2016-08-22 09:32
@pornel did u find a solution or workaround?

**Comment by pornel** [comment] 2016-08-22 11:44
No I haven't.

**Comment by bt** [comment] 2016-09-12 01:05
@pornel @readme42 

Try my PR#42.

- Add `"enhanced-resolve": "git://github.com/bt/enhanced-resolve.git#patch-1"` into your `package.json` file.
- `rm -rf node_modules`
- `npm install`

Try the following configuration in your Webpack config:

```js
resolve: {
  modules: ['node_modules', 'bower_components'],
  descriptionFiles: ['package.json', 'bower.json'],
}
```

Install a Bower component:

`bower install jquery`

You should be able to use import jQuery in your `.js` files.

```js
import 'jquery';
```

If this works, we can get @sokra to merge it in.

**Comment by pornel** [comment] 2016-09-12 07:58
cc @quarterto @rowanbeentje

**Comment by bt** [comment] 2016-09-20 01:21
@pornel Did you have any luck? It's working for me so I'd love to get this confirmed and merged in so I don't need to include my Git repo in all my projects 😉

**Comment by rowanbeentje** [comment] 2016-09-20 10:32
@bt This is likely now with me - @pornel has sadly changed jobs so no longer working on the project he was running into the problem on.  I've tried to replicate this but I don't think he ever committed his webpack2 work, and my lack of familiarity with webpack2 means I can't reproduce this easily (although I'm past the most basic plugin changes I need to work through our fairly complex setup and https://gist.github.com/sokra/27b24881210b56bbaff7 - if those are the only v2 docs?).  I'm also busy with other things right now :(

I suggest if this is now working for you you merge it in and I'll report back later/raise another issue if we're still having problems...

Sorry and thanks :)

**Comment by bt** [comment] 2016-11-19 01:05
Now that #42 has been merged, it'd be good to revisit this issue to see if it's been solved :smile:

**Comment by linaspa** [comment] 2017-02-11 13:12
@bt @pronel @sokra The main problem is enhanced-resolve plugin doesn't support bower.json main field when libraries are listed in an array format. The problem is in "MainFieldPlugin.js" file, where all non-string main fields are being ignored.

Looks like it's an old problem that was not resolved in: #12 #3 . All issues were closed in favor of https://github.com/lpiepiora/bower-webpack-plugin plugin but it looks like the project is being abandoned for a while and doesn't have support for webpack 2.x .

**Comment by linaspasv** [comment] 2017-02-14 14:24
I have made a small plugin to support bower.json main field in array format: https://github.com/codewizz/bower-resolve-webpack-plugin

**Comment by ambischof** [comment] 2017-03-31 16:33
What is currently the status of this issue? It's blocking me from upgrading to webpack 2.

**Comment by mikesherov** [comment] 2017-07-05 18:57
The main issue stems from the fact that the `main` field in `bower.json` can be an array, pointing to multiple files at once, which potential means custom loaders, not just custom resolvers.

Therefore, in order to correctly support bower, enhanced-resolve is not the correct place to do so, and a more full featured set of plugins would be required. Since multiple plugins exist for bower, and since Bower itself no longer recommends you use it, this will have to remain a thing the community supports.

Please feel free to respond to this issue with more information if you think this was closed in error.

**Closed by mikesherov** 2017-07-05 18:57 UTC
