### ISSUE TITLE
AliasFieldPlugin.apply + lodash: resolving the wrong toString

### ISSUE THREAD

**Issue by Fconstant** [webpack/enhanced-resolve#118] opened 2017-09-20 14:46 UTC
When resolving `"./toString"` from `lodash`, [data2 on AliasFieldPlugin.js](https://github.com/webpack/enhanced-resolve/blob/c0797bbcb5d46a44930887c49dc5378b5527cd7a/lib/AliasFieldPlugin.js#L30) is removing the `./` from `"./toString"` of `lodash`, causing `fieldData` to get the default function `toString()` of every object.

Resulting in:
```shell
       var idxQuery = identifier.indexOf("?");
                                  ^

TypeError: identifier.indexOf is not a function
    at Resolver.parse (/Users/fcconstantino/Projects/@products/@crefisa/NetBankApp/node_modules/enhanced-resolve/lib/Resolver.js:181:28)
    at Resolver.<anonymous> (/Users/fcconstantino/Projects/@products/@crefisa/NetBankApp/node_modules/enhanced-resolve/lib/ParsePlugin.js:17:25)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/Users/fcconstantino/Projects/@products/@crefisa/NetBankApp/node_modules/tapable/lib/Tapable.js:256:13)
    at runNormal (/Users/fcconstantino/Projects/@products/@crefisa/NetBankApp/node_modules/enhanced-resolve/lib/Resolver.js:130:20)
    at Resolver.doResolve (/Users/fcconstantino/Projects/@products/@crefisa/NetBankApp/node_modules/enhanced-resolve/lib/Resolver.js:116:3)
    at Resolver.<anonymous> (/Users/fcconstantino/Projects/@products/@crefisa/NetBankApp/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:12)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/Users/fcconstantino/Projects/@products/@crefisa/NetBankApp/node_modules/tapable/lib/Tapable.js:256:13)
    at runNormal (/Users/fcconstantino/Projects/@products/@crefisa/NetBankApp/node_modules/enhanced-resolve/lib/Resolver.js:130:20)
    at Resolver.doResolve (/Users/fcconstantino/Projects/@products/@crefisa/NetBankApp/node_modules/enhanced-resolve/lib/Resolver.js:116:3)
    at Resolver.<anonymous> (/Users/fcconstantino/Projects/@products/@crefisa/NetBankApp/node_modules/enhanced-resolve/lib/AliasFieldPlugin.js:49:12)
```

Something I couldn't find is: Who is calling the `AliasFieldPlugin`?

A simple and easy fix was to do something like this:
```javascript
if (typeof data === 'function') {
    return callback();
}
```

**OBS:** I'm also using [Haul](https://github.com/callstack/haul), which uses an older version of `webpack`, but still the latest version of `enhanced-resolve`

| Using        | Version           |
| ------------- |-------------|
| npm     | 5.4.2 |
| webpack      | 2.7.0      | 
| enhanced-resolve | 3.4.1   |
| lodash      | 4.17.4      | 
| haul   | 1.0.0-beta.5   |

**Comment by omatrot** [comment] 2017-12-17 13:29
I have the same error using [sjcl](https://github.com/bitwiseshiftleft/sjcl) in a ReactJS app using webpack. Works fine in React Native (Babel) though.

**Comment by omatrot** [comment] 2017-12-17 16:40
Solved it by replacing sjcl with jwt-decode because I only need to deal with JWT Tokens

**Comment by sokra** [comment] 2018-01-04 16:10
Send a PR.

``` js
Object.prototype.hasOwnProperty.call(someObject, someProperty)
```

**Comment by Fconstant** [comment] 2018-01-08 12:32
@sokra Sorry, I didn't understand what you meant. What am I supposed to do with `hasOwnProperty`?

**Comment by domoritz** [comment] 2018-01-29 17:47
Could this be causing https://github.com/jupyterlab/jupyter-renderers/issues/91?

**Comment by Fconstant** [comment] 2018-01-30 11:56
@domoritz Almost. In your case `identifier` is `null`. In this case, `identifier` is not null but `indexOf` is not a function (I don't know why). But it is the same location that triggers the error.

**Comment by dylanslade** [comment] 2018-08-30 18:41
Has any progress been made?

**Comment by evilebottnawi** [comment] 2018-08-30 18:42
Need reproducible test repo, thanks!

**Comment by sentenza** [comment] 2018-10-12 21:50
The only workaround I found for this issue is adding:

```json
"browser": {
    "crypto": true
  }
```

to my `package.json`. @evilebottnawi you can find the repo [here](https://github.com/sentenza/ng-solid-material/blob/3b8635c2e0f56c1dac5728be17171edf1409be84/package.json#L13)

**Comment by ArThoX** [comment] 2018-12-30 22:06
Is @sentenza fix working for everyone ? Didnt solve it for me..

**Comment by khalidhoffman** [comment] 2020-01-18 23:35
@ArThoX  I think you may just need to pass some path string instead of a boolean

**Comment by evilebottnawi** [comment] 2020-07-16 15:48
I think here problem with `package.json`, all issue referrer to packages with strange `package.json`:
```json
{
 "browser": {
    "crypto": false
  }
}
```

`browser` should not be object

**Comment by sokra** [comment] 2020-07-16 16:27
I think we need to check hasOwnProperty to avoid receiving Object prototype methods

**Comment by evilebottnawi** [comment] 2020-07-16 16:49
Yep, just want to find broken example

**Comment by pmmmwh** [comment] 2022-04-04 05:17
I think this will break reliably - a couple helpers in `lodash` mutates function prototype, in particular anything related to `_setToString` (e.g. `sortBy`)

```json
{
  "dependencies": {
	"@pmmmwh/react-refresh-webpack-plugin": "0.5.x",
    "expo": "*"
  }
}
```

The issue creeps in via `whatwg-url` which internally uses `lodash/sortBy`.

**Comment by vankop** [comment] 2022-04-04 06:31
yeah, this should be fixed..

**Closed** 2022-04-12 09:32 UTC
